version: 2.1
jobs:
  build:
    working_directory: ~/phobos
    machine:
      image: ubuntu-2604:current
    resource_class: large.gen3
    steps:
      - checkout
      - run:
          command: ./.circleci/run.sh install-deps
          name: Install DMD
      - run:
          command: ./.circleci/run.sh setup-repos
          name: Clone DMD & tools and build DMD & druntime
      - run:
          command: ./.circleci/run.sh publictests
          name: Run all public unittests
      - run:
          command: ./.circleci/run.sh coverage
          name: Run Phobos testsuite with -cov=ctfe
      - run:
          command: ./.circleci/run.sh coverage
          name: Upload coverage files to CodeCov
